apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: csi-driver-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Tenant is the Schema for the tenants API
      displayName: Tenant
      kind: Tenant
      name: tenants.csiprovisioner.kubevirt.io
      version: v1alpha1
  description: KubeVirt CSI driver operator
  displayName: csi-driver-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - csi driver
  - kubevirt
  links:
  - name: Csi Driver Operator
    url: https://csi-driver-operator.domain
  maturity: alpha
  provider:
    name: csi-driver-operator
  version: 0.0.0
